package com.awcsoftware.app.timesheet;

import java.util.List;

import org.apache.ibatis.session.SqlSession;
import org.apache.log4j.Logger;

import com.awcsoftware.app.AppException;
import com.awcsoftware.app.ErrorConstants;
import com.awcsoftware.mybatis.DbException;
import com.awcsoftware.mybatis.MyBatisManager;

public class TimecardDao {
	static Logger logger = Logger.getLogger(TimecardDao.class);

	
	public String addTimecard(TimecardInfo timecardInfo) throws DbException, AppException {
		/*
		 * This needs to be made as a transaction
		 * 
		 * check for data already exist for this emp for this week if true call Dao
		 * Update method - updateTimecardDetails (for each row for each day) else call
		 * Dao add method - addTimecard, addTimecardDetails
		 * 
		 * 
		 * for add fetch the lastest autogenerated id from table set the id for Info
		 * table in Details table
		 * 
		 * 
		 */
		SqlSession session = MyBatisManager.openSession();
		try {
			if (isDataForEmployeeForCurrentWeekExists(timecardInfo) == false) {
				session.insert("TimeSheetSummaryMapper.addTimecardInfo", timecardInfo);
				for (TimecardDetails timecardDetails : timecardInfo.getTimeCardDetails()) {
					timecardDetails.setTcId(timecardInfo.getTcId());
					if (isDataForEmployeeForCurrentDateTimeExists(timecardDetails) == false) {
						return ErrorConstants.TimecardTimeDataExist.getLabel();
					}
				}
				session.insert("TimeSheetSummaryMapper.addTimecardDetails", timecardInfo.getTimeCardDetails());
				session.commit();
				return ErrorConstants.TimecardSuccessMessage.getLabel();
			} else
				return ErrorConstants.TimecardDataExist.getLabel();

		} finally {
			session.close();
		}
	}
	
	public List<TimecardView> getTimecardView(int empId)  throws DbException 
	{
		List<TimecardView> theTimeCardViewObj = null;
		SqlSession session = MyBatisManager.openSession();
		try
		{
			List<TimecardView> lstTimecardView = session.selectList("TimeSheetSummaryMapper.getTimecardView",empId);
			return lstTimecardView;
		} finally {
			session.close();
		}
	}

	public boolean isDataForEmployeeForCurrentWeekExists(TimecardInfo timecardInfo) {
		SqlSession session = MyBatisManager.openSession();
		int itcId = 0;
		try {
			itcId = session.selectOne("TimeSheetSummaryMapper.isDataForEmployeeForCurrentWeekExists", timecardInfo);
			if (itcId == -1)
				return false;
			else
				return true;
		} finally {
			session.close();
		}
	}
	
	public boolean isDataForEmployeeForCurrentDateTimeExists(TimecardDetails timecardDetails) {
		SqlSession session = MyBatisManager.openSession();
		int itcdId = 0;
		try {
			itcdId = session.selectOne("TimeSheetSummaryMapper.isDataForEmployeeForCurrentDateTimeExists",
					timecardDetails);
			if (itcdId == -1)
				return true;
			else
				return false;
		} finally {
			session.close();
		}
	}
	
	public List<TimecardInfo> getTimecardByManager(int approverId){
		SqlSession session = MyBatisManager.openSession();

		try {
			List<TimecardInfo> result = session.selectList("TimeSheetSummaryMapper.getTimecardByManager",approverId);
			if (result!=null)
				return result;
			else
				return null;
		} finally {
			session.close();
		}
		
	}
}
